service: frontcontrolgastos
runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /(.*\.(js|css|svg|png)(|\.map))$
  static_files: dist
  upload: dist/(.*)(|\.map)
  - url: /.*
  static_files: dist/index.html
  upload: dist/.*
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
