export enum HttpStatusCodeEnum {
  ZERO = 0,
  OK = 200,
  ACCEPTED = 202,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBBIDEN = 403,
  NOT_FOUND = 404,
  NOT_ACCEPTABLE = 406,
  CONFLICT = 409,
  PRECONDITION_FAILED = 412,
  EXPECTATION_FAILED = 417,
  UNPROCESSABLE_ENTITY = 422,
  INTERNAL_SERVER_ERROR = 500,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
}

export enum validationType {
  EMAIL_FAIL_VALIDATION = 'Invalid email',
  PASS_FAIL_VALIDATION = 'Invalid password',
}

export enum errorType {
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
}
